In [1]:
import sys

!which {sys.executable}

/ut3/jerome/miniconda3/envs/wakai/bin/python

In [2]:
import sys
sys.path.insert(0, '../code')

# NExSci catalog

In [3]:
from catalog import get_nexsci_data

table = 'pscomppars'
nexsci = get_nexsci_data(table, clobber=False)
nexsci.tail()

2025-09-19 10:34:18.127 | INFO     | catalog:get_nexsci_data:1367 - Column definitions:
/mnt_ut2/raid_ut2/home/jerome/github/research/project/wakai/notebooks/../code/catalog.py:1378: DtypeWarning: Columns (5,6,127,130,350,353,368,396,399,405,408) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fp)
2025-09-19 10:34:18.921 | INFO     | catalog:get_nexsci_data:1379 - Loaded:

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,...,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec,sky_coord.ra,sky_coord.dec
4274,3.36600,Kepler-30 b,b,2.432366,Kepler-30,NaN,NaN,TIC 399794329,2012-07,2012,...,NaN,NaN,0.0,NaN,0.197,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,285.283648,38.947263
4275,3.13144,TOI-1107 b,b,2.573077,TOI-1107,NaN,NaN,TIC 394561119,2022-05,2022,...,NaN,NaN,0.0,NaN,0.199,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,155.607863,-82.218869
4276,3.30200,Kepler-138 c,c,2.508830,Kepler-138,NaN,NaN,TIC 159376971,2014-03,2014,...,NaN,NaN,0.0,NaN,1.370,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,290.381412,43.293064
4277,3.15117,TOI-2374 b,b,2.574933,TOI-2374,NaN,NaN,TIC 439366538,2024-06,2024,...,NaN,NaN,0.0,NaN,0.350,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,319.498241,-22.049823
4278,3.17612,BD-14 3065 b,b,2.577404,BD-14 3065 A,NaN,NaN,TIC 293607057,2024-03,2024,...,NaN,NaN,0.0,NaN,0.111,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,153.669669,-15.642837

nexsci.columns.tolist()

In [4]:
nexsci.shape

(4279, 684)

In [5]:
nexsci.hostname.unique().shape

(3237,)

# cross-match nexsci with Gaia DR3 using `astroquery.xmatch`

In [6]:
import astropy.units as u
from astroquery.xmatch import XMatch
import pandas as pd

gaia_table = XMatch.query(
    cat1=open(f'../data/nexsci_{table}.csv'),
    cat2="vizier:I/355/gaiadr3",  # The Vizier identifier for Gaia DR3
    max_distance=1 * u.arcsec,    # Set the maximum matching radius
    colRA1="ra",  # Column name for Right Ascension in TIC results
    colDec1="dec" # Column name for Declination in TIC results
)
gaia_df = gaia_table.to_pandas()

# results to 6237 matches
matches = gaia_df.copy()

# Apply magnitude filtering criteria
# For main-sequence stars, the difference between TESS T and Gaia G is around 0–0.5 magnitudes
# Redder stars might have T - G values closer to 1–2 magnitudes.
# For giants or highly reddened stars, the difference could be larger.
if False:
    # results to 5971 matches
    matches = []
    for i, row in gaia_df.iterrows():
        teff=row['st_teff']
        if teff<3500:
            magnitude_threshold = 2
        elif (teff>3500) and (teff<6000):
            magnitude_threshold = 1
        else:
            magnitude_threshold = 1.5
        if abs(row['Gmag'] - row['TESS Mag']) < magnitude_threshold:
            matches.append(row)
    matches = pd.concat(matches, axis=1).T
if False:
    # results to 5700 matches
    magnitude_threshold = 1
    matches = gaia_df[abs(gaia_df['Gmag'] - gaia_df['sy_tmag']) < magnitude_threshold]
if False:
    # results to 4878 matches
    teff_threshold = 1000
    matches = gaia_df[abs(gaia_df['Teff'] - gaia_df['st_teff']) < teff_threshold]
matches.head()

Could not import regions, which is required for some of the functionalities of this module.

,angDist,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,...,B_AG,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000
0,0.000790,3.23620,Kepler-1812 b,b,2.454097,Kepler-1812,NaN,NaN,TIC 170346516,2022-02,...,0.3254,0.1656,0.1590,0.1751,MARCS,298.084515,40.283253,0.391880,0.407567,-0.0730
1,0.004019,3.25790,Kepler-1822 b,b,2.476824,Kepler-1822,NaN,NaN,TIC 169177842,2022-02,...,0.1343,0.0468,0.0283,0.0714,MARCS,297.285489,41.305606,0.476402,0.491835,-0.1586
2,0.026341,3.91950,K2-347 b,b,2.198018,K2-347,NaN,NaN,TIC 14603874,2016-10,...,0.2006,0.0961,0.0906,0.1058,MARCS,126.372926,23.297377,0.420547,0.296408,-0.3926
3,0.005877,3.10327,K2-343 c,c,2.193496,K2-343,NaN,NaN,TIC 197246627,2018-07,...,0.4557,0.2620,0.2602,0.2636,MARCS,134.202226,21.502673,0.579617,0.382229,-0.2577
4,0.009381,3.91440,K2-332 b,b,2.164596,K2-332,NaN,NaN,TIC 330621494,2016-10,...,0.5747,0.3649,0.3576,0.3783,MARCS,135.883336,14.250545,0.982793,0.762718,-0.2331

In [7]:
matches.shape

(4313, 822)

In [8]:
matches.hostname.unique().shape

(3235,)

In [9]:
matches['GaiaDR3'] = matches['DR3Name'].apply(lambda x: int(x.split()[-1]))
matches.to_csv('../data/nexsci_GaiaDR3_xmatch.csv', index=False)

In [10]:
idx = nexsci.hostname.isin(matches.hostname.unique())
nexsci[~idx].shape

(2, 684)

In [11]:
nexsci[~idx].to_csv('../data/nexsci_GaiaDR3_xmatch_missing.csv', index=False)

import pandas as pd

matches = pd.read_csv('../data/nexsci_GaiaDR3_xmatch.csv')
matches.head()