In [1]:
import sys

!which {sys.executable}

/ut3/jerome/miniconda3/envs/wakai/bin/python

In [2]:
import sys
sys.path.insert(0, '../code')

%load init_ipynb

# Perren+2023 catalog

In [19]:
import pandas as pd

catalog_name = 'Perren2023'
df = pd.read_csv('../data/Perren2023/UCC_cat.csv.gz')
df.tail()

,ID,RA_ICRS,DE_ICRS,plx,pmRA,pmDE,UCC_ID,N_50,r_50,RA_ICRS_m,DE_ICRS_m,plx_m,pmRA_m,pmDE_m,Rv_m,N_Rv,C1,C2,C3
16174,MKN 1;MKN ab,266.4468,-29.0874,NaN,NaN,NaN,UCC G359.8-00.1,79.0,4.4,266.462,-29.095,0.489,1.753,-0.777,-25.868,5.0,0.86,0.75,AA
16175,MWSC 5326,248.1925,-17.1430,NaN,NaN,NaN,UCC G359.9+20.4,0.0,4.6,248.189,-17.148,0.090,-3.735,-5.860,67.828,1.0,0.11,0.20,DD
16176,HSC 2986,285.3171,-36.8834,6.694,2.209,-27.556,UCC G359.9-17.7,0.0,22.5,285.298,-36.941,6.532,3.670,-27.737,-5.275,8.0,0.72,1.00,BA
16177,VVV 149;VVV-CL 149,267.3380,-29.4640,NaN,NaN,NaN,UCC G359.9-00.9,0.0,2.6,267.351,-29.455,0.352,-0.674,-2.780,-39.904,3.0,0.45,0.46,CC
16178,Ryu 535,266.5884,-29.0573,NaN,NaN,NaN,UCC G359.9-00.2,61.0,2.1,266.606,-29.055,0.376,-0.153,-2.099,-33.921,4.0,0.88,0.31,AC

In [4]:
df_mem = pd.read_parquet('../data/Perren2023/UCC_members.parquet.gz')
df_mem.tail()

,name,Source,RA_ICRS,DE_ICRS,Plx,e_Plx,pmRA,e_pmRA,pmDE,e_pmDE,RV,e_RV,GLON,GLAT,Gmag,BP-RP,e_Gmag,e_BP-RP,probs
1337412,ryu30,5933719906152539904,247.228085,-52.699637,0.240993,0.158018,-4.525831,0.154389,-4.983059,0.127764,NaN,NaN,332.477863,-2.781450,18.330563,2.435881,0.003246,0.088112,0.46891
1337413,ryu30,5933720318469495424,247.180385,-52.706245,0.135389,0.053207,-4.841031,0.055405,-5.292475,0.045611,NaN,NaN,332.453112,-2.765083,16.444132,1.731100,0.002817,0.009220,0.45149
1337414,ryu30,5933720107969318016,247.178643,-52.736859,0.300294,0.121510,-4.620295,0.120153,-5.140017,0.103496,NaN,NaN,332.430199,-2.785444,17.966627,1.370831,0.002976,0.017981,0.45149
1337415,ryu30,5933720490268392704,247.119139,-52.692309,0.270647,0.230620,-4.524732,0.220578,-4.939661,0.182071,NaN,NaN,332.437554,-2.728610,18.863051,2.578410,0.003619,0.063381,0.41418
1337416,ryu30,5933730587694794880,247.078632,-52.721215,0.231349,0.169833,-4.648944,0.173652,-4.778104,0.143794,NaN,NaN,332.399658,-2.730834,18.484586,NaN,0.003323,NaN,0.40547

In [5]:
#replace name to be compatible with other catalogs' naming formats
df_mem = df_mem.rename({"name": "Name",
                        "Source": "GaiaDR3",
                        "probs": "Prob",
                        "RA_ICRS": "ra",
                        "DE_ICRS": "dec",
                        "pmRA": "pmra",
                        "pmDE": "pmdec",
                        "Plx": "parallax",
                        "RV": "radial_velocity"
                        }, axis=1)
df_mem

,Name,GaiaDR3,ra,dec,parallax,e_Plx,pmra,e_pmRA,pmdec,e_pmDE,radial_velocity,e_RV,GLON,GLAT,Gmag,BP-RP,e_Gmag,e_BP-RP,Prob
0,teutsch288,2035397237977138688,297.899779,34.283035,0.145318,0.024893,-2.974327,0.023901,-5.158872,0.030316,-37.576607,4.797507,69.829982,3.785472,15.418702,2.254350,0.002774,0.005336,0.99767
1,teutsch288,2035389575755522944,297.965276,34.067585,0.145510,0.027632,-2.991828,0.030353,-5.123003,0.031205,NaN,NaN,69.671655,3.629290,15.662445,2.212796,0.002788,0.006342,0.98601
2,teutsch288,2035488463077136512,298.127866,34.400420,0.103535,0.027940,-3.008745,0.025883,-5.085567,0.030720,NaN,NaN,70.027281,3.683075,15.776573,2.014382,0.002781,0.005409,0.95804
3,teutsch288,2035393458405832448,298.028314,34.250542,0.288494,0.011875,-3.031625,0.012742,-5.184984,0.013464,-14.070918,0.746670,69.856073,3.677483,13.459954,2.037782,0.002763,0.004934,0.86946
4,teutsch288,2035491486734157440,298.106791,34.426259,0.070932,0.015924,-2.982798,0.014108,-5.185106,0.016694,-45.478336,1.353905,70.040681,3.711202,14.410107,2.713133,0.002785,0.005189,0.86946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1337412,ryu30,5933719906152539904,247.228085,-52.699637,0.240993,0.158018,-4.525831,0.154389,-4.983059,0.127764,NaN,NaN,332.477863,-2.781450,18.330563,2.435881,0.003246,0.088112,0.46891
1337413,ryu30,5933720318469495424,247.180385,-52.706245,0.135389,0.053207,-4.841031,0.055405,-5.292475,0.045611,NaN,NaN,332.453112,-2.765083,16.444132,1.731100,0.002817,0.009220,0.45149
1337414,ryu30,5933720107969318016,247.178643,-52.736859,0.300294,0.121510,-4.620295,0.120153,-5.140017,0.103496,NaN,NaN,332.430199,-2.785444,17.966627,1.370831,0.002976,0.017981,0.45149
1337415,ryu30,5933720490268392704,247.119139,-52.692309,0.270647,0.230620,-4.524732,0.220578,-4.939661,0.182071,NaN,NaN,332.437554,-2.728610,18.863051,2.578410,0.003619,0.063381,0.41418
1337416,ryu30,5933730587694794880,247.078632,-52.721215,0.231349,0.169833,-4.648944,0.173652,-4.778104,0.143794,NaN,NaN,332.399658,-2.730834,18.484586,NaN,0.003323,NaN,0.40547

In [6]:
from catalog import get_nexsci_data

table='pscomppars'
nexsci = get_nexsci_data(table, clobber=False)
nexsci.tail()

2025-09-19 10:45:26.465 | INFO     | catalog:get_nexsci_data:1367 - Column definitions:
/mnt_ut2/raid_ut2/home/jerome/github/research/project/wakai/notebooks/../code/catalog.py:1378: DtypeWarning: Columns (5,6,127,130,350,353,368,396,399,405,408) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fp)
2025-09-19 10:45:26.973 | INFO     | catalog:get_nexsci_data:1379 - Loaded:

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,...,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec,sky_coord.ra,sky_coord.dec
4274,3.36600,Kepler-30 b,b,2.432366,Kepler-30,NaN,NaN,TIC 399794329,2012-07,2012,...,NaN,NaN,0.0,NaN,0.197,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,285.283648,38.947263
4275,3.13144,TOI-1107 b,b,2.573077,TOI-1107,NaN,NaN,TIC 394561119,2022-05,2022,...,NaN,NaN,0.0,NaN,0.199,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,155.607863,-82.218869
4276,3.30200,Kepler-138 c,c,2.508830,Kepler-138,NaN,NaN,TIC 159376971,2014-03,2014,...,NaN,NaN,0.0,NaN,1.370,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,290.381412,43.293064
4277,3.15117,TOI-2374 b,b,2.574933,TOI-2374,NaN,NaN,TIC 439366538,2024-06,2024,...,NaN,NaN,0.0,NaN,0.350,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,319.498241,-22.049823
4278,3.17612,BD-14 3065 b,b,2.577404,BD-14 3065 A,NaN,NaN,TIC 293607057,2024-03,2024,...,NaN,NaN,0.0,NaN,0.111,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,153.669669,-15.642837

nexsci.columns.tolist()

In [7]:
nexsci.shape

(4279, 684)

In [8]:
if table=='ps':
    nexsci_hosts = nexsci[nexsci['default_flag']==1]
else:
    nexsci_hosts = nexsci.copy()
nexsci_hosts.shape

(4279, 684)

In [9]:
nexsci.hostname.unique().shape

(3237,)

# cross-match nexsci with catalog

In [10]:
import pandas as pd

if True:
    #from astroquery.xmatch
    matches = pd.read_csv('../data/nexsci_GaiaDR3_xmatch.csv')
if False:
    #from vizier query/exofop; not yet available
    matches = pd.read_csv('../data/nexsci_with_Gaiaid.csv')
    matches['GaiaDR3'] = matches['GaiaDR3_vizier']
matches.head()

/tmp/ipykernel_1757265/1889420029.py:5: DtypeWarning: Columns (7,101,104,128,131,351,354,360,363,397,400,406,409,452,455,461,464) have mixed types. Specify dtype option on import or set low_memory=False.
  matches = pd.read_csv('../data/nexsci_GaiaDR3_xmatch.csv')

,angDist,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,...,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000,GaiaDR3
0,0.000790,3.23620,Kepler-1812 b,b,2.454097,Kepler-1812,NaN,NaN,TIC 170346516,2022-02,...,0.1656,0.1590,0.1751,MARCS,298.084515,40.283253,0.391880,0.407567,-0.0730,2073767994738269952
1,0.004019,3.25790,Kepler-1822 b,b,2.476824,Kepler-1822,NaN,NaN,TIC 169177842,2022-02,...,0.0468,0.0283,0.0714,MARCS,297.285489,41.305606,0.476402,0.491835,-0.1586,2076881364987303296
2,0.026341,3.91950,K2-347 b,b,2.198018,K2-347,NaN,NaN,TIC 14603874,2016-10,...,0.0961,0.0906,0.1058,MARCS,126.372926,23.297377,0.420547,0.296408,-0.3926,678119333962115072
3,0.005877,3.10327,K2-343 c,c,2.193496,K2-343,NaN,NaN,TIC 197246627,2018-07,...,0.2620,0.2602,0.2636,MARCS,134.202226,21.502673,0.579617,0.382229,-0.2577,685818492336147072
4,0.009381,3.91440,K2-332 b,b,2.164596,K2-332,NaN,NaN,TIC 330621494,2016-10,...,0.3649,0.3576,0.3783,MARCS,135.883336,14.250545,0.982793,0.762718,-0.2331,607158571490718208

In [11]:
final = pd.merge(df_mem, matches, on='GaiaDR3')
final.head()

,Name,GaiaDR3,ra_x,dec_x,parallax,e_Plx_x,pmra,e_pmRA_x,pmdec,e_pmDE_x,...,B_AG,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000
0,ocsn22,2128840912955018368,293.947637,48.065259,3.785336,0.011156,2.935962,0.013675,2.083320,0.012898,...,0.3911,0.2019,0.1760,0.2074,PHOENIX,293.947618,48.065250,0.219181,0.208884,0.0412
1,ngc6866,2081880913079644288,301.278685,44.250511,0.668770,0.027363,-1.461941,0.030144,-5.878610,0.030611,...,0.2221,0.1001,0.0865,0.1195,MARCS,301.278694,44.250537,0.482553,0.496461,-0.0153
2,hsc569,2101379205604338688,289.625219,40.708735,3.015305,0.018630,-2.738502,0.019622,1.652388,0.024012,...,NaN,NaN,NaN,NaN,NaN,289.625235,40.708728,0.314476,0.388348,0.0058
3,cwnu375,2103737241426734336,284.056668,41.576728,3.008675,0.031928,1.715656,0.033676,-1.315201,0.033636,...,0.0555,0.0249,0.0192,0.0299,MARCS,284.056658,41.576733,0.544167,0.545054,0.0328
4,hsc572,2052827207364859264,290.440629,38.523572,3.056519,0.009273,-4.153693,0.010347,2.269135,0.010561,...,0.1674,0.0791,0.0713,0.0894,MARCS,290.440652,38.523562,0.165626,0.171329,-0.0537

In [12]:
final[['pl_name','Name']]

             pl_name                 Name
0         KOI-7368 b               ocsn22
1      Kepler-1915 b              ngc6866
2       Kepler-970 b               hsc569
3      Kepler-1627 b              cwnu375
4      Kepler-1928 b               hsc572
5        Kepler-67 b              ngc6811
6        Kepler-66 b              ngc6811
7           K2-231 b           cwwdl14561
8           K2-231 b              ngc6774
9            K2-25 b  taurusmovingcluster
10       V1298 Tau d             cwnu1094
11       V1298 Tau b             cwnu1094
12       V1298 Tau c             cwnu1094
13       V1298 Tau e             cwnu1094
14          K2-100 b              ngc2632
15          K2-104 b              ngc2632
16          K2-264 c              ngc2632
17          K2-264 b              ngc2632
18          K2-101 b              ngc2632
19           K2-95 b              ngc2632
20          K2-102 b              ngc2632
21  EPIC 211822797 b              ngc2632
22           K2-33 b              ocsn100
23         TOI-837 b           melotte102
24        TOI-1227 b              hsc2523

In [13]:
final.hostname.unique().shape

(20,)

In [16]:
if table=='ps':
    final_default = final[final['default_flag']==1]
else:
    final_default = final.copy()
final_default.shape

(25, 841)

In [21]:
final_default.sort_values(by='pl_name')\
    .to_csv(f'../data/{catalog_name}/nexsci_in_{catalog_name}.csv', 
            index=False)