In [1]:
import sys

!which {sys.executable}

/ut3/jerome/miniconda3/envs/wakai/bin/python

In [2]:
import sys
sys.path.insert(0, '../code')

%load init_ipynb

# Hunt+2024 catalog

https://ucc.ar/_clusters/ngc1039/

In [3]:
from catalog import CatalogDownloader

cd = CatalogDownloader(catalog_name="Hunt2024", catalog_type="cluster")
tabs = cd.get_tables_from_vizier(row_limit=-1, save=True)

2025-09-19 10:27:10.647 | INFO     | catalog:get_vizier_url:1204 - Data url: https://vizier.u-strasbg.fr/viz-bin/VizieR?-source=J/A+A/686/A42
2025-09-19 10:27:10.649 | INFO     | catalog:get_tables_from_vizier:1156 - Downloading all tables in J/A+A/686/A42 from vizier.
2025-09-19 10:28:28.934 | INFO     | catalog:save_tables:1195 - Set clobber=True to overwrite.
2025-09-19 10:28:28.935 | INFO     | catalog:save_tables:1195 - Set clobber=True to overwrite.
2025-09-19 10:28:28.936 | INFO     | catalog:save_tables:1195 - Set clobber=True to overwrite.

{'J/A+A/686/A42/clusters': 'Main catalogue (table 1)',
 'J/A+A/686/A42/crossma': 'All (non-)xmatched clusters',
 'J/A+A/686/A42/members': 'Member stars of clusters (table 2)'}

In [4]:
df = tabs[0].to_pandas()
df_mem = tabs[1].to_pandas()
df_mem.head()

,Name,ID,GaiaDR3,inrt,Prob,RA_ICRS,DE_ICRS,pmRA,pmDE,Plx,Gmag,BPmag,RPmag,RV,_RA.icrs,_DE.icrs
0,ADS_16795,1,1996314203783884544,1,1.0,345.384660,53.575661,17.900614,3.016996,4.764468,15.888477,17.284605,14.729848,NaN,345.384526,53.575648
1,ADS_16795,1,1997123787936918656,1,1.0,349.375671,55.888239,18.823945,3.521466,4.850097,15.854546,17.097689,14.749281,NaN,349.375522,55.888223
2,ADS_16795,1,1997227928003678848,1,1.0,350.228229,56.225701,19.058485,2.543160,4.727565,17.689924,19.592110,16.372536,NaN,350.228076,56.225690
3,ADS_16795,1,1998973608873873152,1,1.0,354.235696,58.135253,19.450099,1.870025,4.581254,16.649845,18.253677,15.427638,NaN,354.235532,58.135244
4,ADS_16795,1,2002532006459866240,1,1.0,342.869732,53.892829,17.181225,3.968470,4.790819,15.987680,17.472708,14.779086,NaN,342.869602,53.892811

In [5]:
#replace name to be compatible with other catalogs' naming formats
df_mem = df_mem.rename({#"Cluster": "Name",
                        # "Source": "GaiaDR3",
                        # "Proba": "Prob",
                        "RA_ICRS": "ra",
                        "DE_ICRS": "dec",
                        "pmRA": "pmra",
                        "pmDE": "pmdec",
                        "Plx": "parallax",
                        "RV": "radial_velocity"
                        }, axis=1)
df_mem.head()

,Name,ID,GaiaDR3,inrt,Prob,ra,dec,pmra,pmdec,parallax,Gmag,BPmag,RPmag,radial_velocity,_RA.icrs,_DE.icrs
0,ADS_16795,1,1996314203783884544,1,1.0,345.384660,53.575661,17.900614,3.016996,4.764468,15.888477,17.284605,14.729848,NaN,345.384526,53.575648
1,ADS_16795,1,1997123787936918656,1,1.0,349.375671,55.888239,18.823945,3.521466,4.850097,15.854546,17.097689,14.749281,NaN,349.375522,55.888223
2,ADS_16795,1,1997227928003678848,1,1.0,350.228229,56.225701,19.058485,2.543160,4.727565,17.689924,19.592110,16.372536,NaN,350.228076,56.225690
3,ADS_16795,1,1998973608873873152,1,1.0,354.235696,58.135253,19.450099,1.870025,4.581254,16.649845,18.253677,15.427638,NaN,354.235532,58.135244
4,ADS_16795,1,2002532006459866240,1,1.0,342.869732,53.892829,17.181225,3.968470,4.790819,15.987680,17.472708,14.779086,NaN,342.869602,53.892811

get_nexsci_data??

In [9]:
from catalog import get_nexsci_data

table='pscomppars'
nexsci = get_nexsci_data(table, clobber=False)
nexsci.tail()

2025-09-19 10:32:04.490 | INFO     | catalog:get_nexsci_data:1367 - Column definitions:
/mnt_ut2/raid_ut2/home/jerome/github/research/project/wakai/notebooks/../code/catalog.py:1378: DtypeWarning: Columns (5,6,127,130,350,353,368,396,399,405,408) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fp)
2025-09-19 10:32:06.172 | INFO     | catalog:get_nexsci_data:1379 - Loaded:

,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,...,pl_angseperr1,pl_angseperr2,pl_angseplim,pl_angsepformat,pl_angsepstr,pl_angsepsymerr,pl_angsep_reflink,pl_ndispec,sky_coord.ra,sky_coord.dec
4274,3.36600,Kepler-30 b,b,2.432366,Kepler-30,NaN,NaN,TIC 399794329,2012-07,2012,...,NaN,NaN,0.0,NaN,0.197,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,285.283648,38.947263
4275,3.13144,TOI-1107 b,b,2.573077,TOI-1107,NaN,NaN,TIC 394561119,2022-05,2022,...,NaN,NaN,0.0,NaN,0.199,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,155.607863,-82.218869
4276,3.30200,Kepler-138 c,c,2.508830,Kepler-138,NaN,NaN,TIC 159376971,2014-03,2014,...,NaN,NaN,0.0,NaN,1.370,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,290.381412,43.293064
4277,3.15117,TOI-2374 b,b,2.574933,TOI-2374,NaN,NaN,TIC 439366538,2024-06,2024,...,NaN,NaN,0.0,NaN,0.350,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,319.498241,-22.049823
4278,3.17612,BD-14 3065 b,b,2.577404,BD-14 3065 A,NaN,NaN,TIC 293607057,2024-03,2024,...,NaN,NaN,0.0,NaN,0.111,NaN,<a refstr=CALCULATED_VALUE href=/docs/pscp_cal...,0,153.669669,-15.642837

nexsci.columns.tolist()

In [11]:
nexsci.shape

(4279, 684)

In [14]:
if table=='ps':
    nexsci_hosts = nexsci[nexsci['default_flag']==1]
else:
    nexsci_hosts = nexsci.copy()
nexsci_hosts.shape

(4279, 684)

In [15]:
nexsci.hostname.unique().shape

(3237,)

# cross-match nexsci with catalog

In [16]:
import pandas as pd

if True:
    #from astroquery.xmatch
    matches = pd.read_csv('../data/nexsci_GaiaDR3_xmatch.csv')
if False:
    #from vizier query/exofop; not yet available
    matches = pd.read_csv('../data/nexsci_with_Gaiaid.csv')
    matches['GaiaDR3'] = matches['GaiaDR3_vizier']
matches.head()

/tmp/ipykernel_1737980/1889420029.py:5: DtypeWarning: Columns (7,101,104,128,131,351,354,360,363,397,400,406,409,452,455,461,464) have mixed types. Specify dtype option on import or set low_memory=False.
  matches = pd.read_csv('../data/nexsci_GaiaDR3_xmatch.csv')

,angDist,objectid,pl_name,pl_letter,hostid,hostname,hd_name,hip_name,tic_id,disc_pubdate,...,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000,GaiaDR3
0,0.000790,3.23620,Kepler-1812 b,b,2.454097,Kepler-1812,NaN,NaN,TIC 170346516,2022-02,...,0.1656,0.1590,0.1751,MARCS,298.084515,40.283253,0.391880,0.407567,-0.0730,2073767994738269952
1,0.004019,3.25790,Kepler-1822 b,b,2.476824,Kepler-1822,NaN,NaN,TIC 169177842,2022-02,...,0.0468,0.0283,0.0714,MARCS,297.285489,41.305606,0.476402,0.491835,-0.1586,2076881364987303296
2,0.026341,3.91950,K2-347 b,b,2.198018,K2-347,NaN,NaN,TIC 14603874,2016-10,...,0.0961,0.0906,0.1058,MARCS,126.372926,23.297377,0.420547,0.296408,-0.3926,678119333962115072
3,0.005877,3.10327,K2-343 c,c,2.193496,K2-343,NaN,NaN,TIC 197246627,2018-07,...,0.2620,0.2602,0.2636,MARCS,134.202226,21.502673,0.579617,0.382229,-0.2577,685818492336147072
4,0.009381,3.91440,K2-332 b,b,2.164596,K2-332,NaN,NaN,TIC 330621494,2016-10,...,0.3649,0.3576,0.3783,MARCS,135.883336,14.250545,0.982793,0.762718,-0.2331,607158571490718208

In [17]:
final = pd.merge(df_mem, matches, on='GaiaDR3')
final.head()

,Name,ID,GaiaDR3,inrt,Prob,ra_x,dec_x,pmra,pmdec,parallax,...,B_AG,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000
0,HSC_572,2256,2052827207364859264,1,1.000000,290.440629,38.523572,-4.153693,2.269135,3.056519,...,0.1674,0.0791,0.0713,0.0894,MARCS,290.440652,38.523562,0.165626,0.171329,-0.0537
1,HSC_759,2418,1404488390652463872,1,0.699139,237.924104,52.306308,-10.254686,-1.403748,8.591641,...,0.0902,0.0454,0.0435,0.0475,MARCS,237.924179,52.306314,0.211115,0.242307,-0.0190
2,HSC_1340,2875,51886335968692480,1,0.580337,61.331655,20.157030,5.412668,-16.051628,9.257706,...,0.1315,0.0592,0.0532,0.0702,MARCS,61.331629,20.157101,0.471496,0.208515,-0.1653
3,HSC_1340,2875,51886335968692480,1,0.580337,61.331655,20.157030,5.412668,-16.051628,9.257706,...,0.1315,0.0592,0.0532,0.0702,MARCS,61.331629,20.157101,0.471496,0.208515,-0.1653
4,HSC_1340,2875,51886335968692480,1,0.580337,61.331655,20.157030,5.412668,-16.051628,9.257706,...,0.1315,0.0592,0.0532,0.0702,MARCS,61.331629,20.157101,0.471496,0.208515,-0.1653

In [18]:
final[['pl_name','Name']]

             pl_name            Name
0      Kepler-1928 b         HSC_572
1         TOI-2048 b         HSC_759
2        V1298 Tau d        HSC_1340
3        V1298 Tau b        HSC_1340
4        V1298 Tau c        HSC_1340
5        V1298 Tau e        HSC_1340
6          TOI-451 b        HSC_1923
7          TOI-451 c        HSC_1923
8          TOI-451 d        HSC_1923
9         TOI-1227 b        HSC_2523
10         TOI-837 b         IC_2602
11          K2-136 c      Melotte_25
12          K2-136 d      Melotte_25
13          K2-136 b      Melotte_25
14           K2-25 b      Melotte_25
15  EPIC 211822797 b        NGC_2632
16           K2-95 b        NGC_2632
17          K2-101 b        NGC_2632
18          K2-264 c        NGC_2632
19          K2-264 b        NGC_2632
20          K2-102 b        NGC_2632
21          K2-104 b        NGC_2632
22          K2-100 b        NGC_2632
23       Kepler-67 b        NGC_6811
24       Kepler-66 b        NGC_6811
25     Kepler-1915 b        NGC_6866
26           K2-33 b        OCSN_100
27          K2-231 b    Ruprecht_147
28        DS Tuc A b  beta_Tuc_Group

In [19]:
final.hostname.unique().shape

(21,)

In [18]:
final_default = final[final['default_flag']==1]
final_default.shape

(29, 510)

In [21]:
final_default.sort_values(by='pl_name')\
    .to_csv(f'../data/{cd.catalog_name}/nexsci_in_{cd.catalog_name}.csv', 
            index=False)